# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

################################################################################

includes:
- ../app_locations.yml
- ../engine_locations.yml
- ./tk-multi-data-validation.yml
- ./tk-multi-loader2.yml
- ./tk-multi-publish2.yml
- ./tk-multi-reviewsubmission.yml
- ./tk-multi-screeningroom.yml
- ./tk-multi-shotgunpanel.yml
- ./tk-multi-snapshot.yml
- ./tk-multi-workfiles2.yml
- ./tk-multi-breakdown2.yml
- ./tk-gundam-publish2.yml #지우면 ㅈ됨 

################################################################################

# asset
settings.tk-maya.asset:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  debug_logging: false
  location: "@engines.tk-maya.location"

# asset_step
settings.tk-maya.asset_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-breakdown:
      display_name: "Legacy Breakdown"
      location: "@apps.tk-multi-breakdown.location"
    tk-multi-breakdown2: "@settings.tk-multi-breakdown2.maya"
    tk-multi-data-validation: "@settings.tk-multi-data-validation.maya.asset_step"
    tk-multi-loader2: "@settings.tk-multi-loader2.maya" #원체 존재
    # tk-multi-publish2: "@settings.tk-multi-publish2.maya.asset_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.maya"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.maya.asset_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.maya.asset_step"
    tk-multi-reviewsubmission: "@settings.tk-multi-reviewsubmission.maya"
    tk-multi-referencemanager: # 내가 추가한거 (37-38)
      location: {type: dev, path: /home/rapa/westworld_serin/tk-multi-referencemanager}

  
    #엥 이거쓰니까 해결됨 ㅁㅊ 
    tk-multi-publish2:
      location:
        type: app_store
        name: tk-multi-publish2
        version: v2.10.3
      settings: "@settings.tk-multi-publish2.maya.asset_step"
    #이거하니까 낫밷
    tk-gundam-publish2:
      location:
        type: dev
        path: /home/rapa/westworld_serin/configfile_gundam_4/install/app_store/tk-gundam-publish2
      settings: "@settings.tk-gundam-publish2.maya.asset_step"
    # #찾았다이새끼 
    # tk-gundam-publish2: "@settings.tk-gundam-publish2.maya.asset_step"
    # # tk-gundam-publish2: # 여기까지 쓰는거
    # #   location: {type: dev, path: /home/rapa/westworld_serin/tk-gundam-publish2}
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-loader2, name: Loader}  #  이 줄 추가!
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  - {app_instance: tk-multi-breakdown2, name: Scene Breakdown...}
  - {app_instance: tk-multi-referencemanager, name: Reference Manager} # 추가
  - {app_instance: tk-gundam-publish2, name: Gundam Publish...} 
  
  template_project: asset_work_area_maya
  location: "@engines.tk-maya.location"

# project (전부 공용으로 쓰는 것 )
settings.tk-maya.project:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-pythonconsole: #마법사 가라사대
      location: "@apps.tk-multi-pythonconsole.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-maya.location"

# sequence
settings.tk-maya.sequence:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"

  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}

  location: "@engines.tk-maya.location"

# shot
settings.tk-maya.shot:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.launch_at_startup"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  location: "@engines.tk-maya.location"

# shot_step (샷에서 열었을때)
settings.tk-maya.shot_step:
  apps:
    tk-multi-about:
      location: "@apps.tk-multi-about.location"
    tk-multi-setframerange:
      location: "@apps.tk-multi-setframerange.location"
    tk-multi-breakdown:
      display_name: "Legacy Breakdown"
      location: "@apps.tk-multi-breakdown.location"
    tk-multi-breakdown2: "@settings.tk-multi-breakdown2.maya"
    tk-multi-data-validation: "@settings.tk-multi-data-validation.maya.shot_step"
    tk-multi-loader2: "@settings.tk-multi-loader2.maya"  # (원래부터 존재했음) 
    tk-multi-publish2: "@settings.tk-multi-publish2.maya.shot_step"
    tk-multi-screeningroom: "@settings.tk-multi-screeningroom.rv"
    tk-multi-shotgunpanel: "@settings.tk-multi-shotgunpanel.maya"
    tk-multi-snapshot: "@settings.tk-multi-snapshot.maya.shot_step"
    tk-multi-workfiles2: "@settings.tk-multi-workfiles2.maya.shot_step"
    tk-multi-reviewsubmission: "@settings.tk-multi-reviewsubmission.maya"
    # tk-multi-referencemanager: # 내가 추가한거 (37-38)
    #   location: {type: dev, path: /home/rapa/westworld_serin/tk-multi-referencemanager}
    tk-multi-referencemanager:
      location: "@apps.tk-multi-referencemanager.location"
    tk-gundam-publish2: "@settings.tk-gundam-publish2.maya.asset_step"
  menu_favourites:
  - {app_instance: tk-multi-workfiles2, name: File Open...}
  - {app_instance: tk-multi-loader2, name: Loader}  #  줄 추가!
  - {app_instance: tk-multi-snapshot, name: Snapshot...}
  - {app_instance: tk-multi-workfiles2, name: File Save...}
  - {app_instance: tk-multi-publish2, name: Publish...}
  - {app_instance: tk-multi-breakdown2, name: Scene Breakdown...}
  - {app_instance: tk-multi-referencemanager, name: Reference Manager} # 추가
  - {app_instance: tk-gundam-publish2, name: TEST Publish...}

  template_project: shot_work_area_maya
  location: "@engines.tk-maya.location"
