# Flow Production Tracking Toolkit configuration file
# This file was automatically created by tank clone
# This file reflects the paths in the pipeline configuration
# entity which is associated with this location (primary_serin_gundam4th ).

Windows: ''
Darwin: ''
Linux: '/home/rapa/westworld_serin/configfile_gundam_4'

# End of file.
